### ISSUE TITLE
TODO: Update to modern ES6/ES7/ESnext and Fastify

### ISSUE THREAD

**Issue by jasnell** [nearform/acmeair-nodejs#3]
@robbdempsey

The Acmeair sample was first written in 2015 and has not been updated in some time. It would be good to have a "modern" version of the sample.

* [x] Use Fastify (https://github.com/nearform/acmeair-nodejs/pull/2)
* [x] Use Promises / async/await where possible - The current code makes extensive use of callbacks.
* [x] Use Pino for logging - The current code uses log4j
* [x] Update dependencies
* [x] Identify and Improve performance bottlenecks

/cc @conoro @dberesford @mcollina

**Comment by robbdempsey** [comment]
@jasnell when #7 lands I'm not sure what else can be done here. I have another issue to work on related to clinic that I'm going to shift too.  if you have ideas on what to do next let me know.

**Comment by jasnell** [comment]
@robbdempsey ... Thank you very much for the work on this. Excellent stuff.

**Comment by robbdempsey** [comment]
@jasnell do you want me to PR this upstream in acmeair?

**Comment by jasnell** [comment]
Would love that, yes. Thank you!

**Comment by robbdempsey** [comment]
@jasnell 

https://github.com/acmeair/acmeair-nodejs/pull/20

**Comment by mcollina** [comment]
@robbdempsey it would be good to include some basic improvements done in that PR to show how more performant is now.
